import { Lead, Signal } from "./types";

// ---------------------------------------------------------------------------
// AI outreach drafting.
//
// If ANTHROPIC_API_KEY is set, drafts are generated by Claude grounded in the
// live SerpApi signals (this is the "AI experience improved by live search
// data" story for the SerpApi challenge). Without a key, falls back to a
// deterministic template so the app still demos end-to-end.
// ---------------------------------------------------------------------------

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = "claude-sonnet-4-5";

export async function draftOutreach(
  lead: Lead,
  signals: Signal[]
): Promise<{ subject: string; body: string; generated_by: "claude" | "template_fallback" }> {
  if (ANTHROPIC_API_KEY) {
    try {
      return await draftWithClaude(lead, signals);
    } catch {
      // fall through to template
    }
  }
  return draftWithTemplate(lead, signals);
}

async function draftWithClaude(lead: Lead, signals: Signal[]) {
  const signalText = signals
    .map((s) => `- [${s.source}] ${s.headline}${s.snippet ? ` — ${s.snippet}` : ""}`)
    .join("\n");

  const prompt = `You are a sales rep at a company that sells B2B software. Write a short, specific,
non-generic cold outreach email to the contact below. Ground it in the live
signals provided — reference at least one concretely. No fluff, no "I hope
this finds you well". 90-130 words. Return strict JSON: {"subject": "...", "body": "..."}.

Contact: ${lead.contact_name}, ${lead.contact_title ?? "Unknown title"} at ${lead.company_name}
Notes on this lead: ${lead.notes ?? "none"}

Live signals about ${lead.company_name}:
${signalText || "none available"}`;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY!,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 400,
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!res.ok) throw new Error(`Anthropic API error: ${res.status}`);
  const data = await res.json();
  const text = data.content?.[0]?.text ?? "{}";
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  const parsed = JSON.parse(jsonMatch ? jsonMatch[0] : text);
  return {
    subject: parsed.subject ?? `Quick note for ${lead.contact_name}`,
    body: parsed.body ?? text,
    generated_by: "claude" as const,
  };
}

function draftWithTemplate(lead: Lead, signals: Signal[]) {
  const priority = { serpapi_news: 0, serpapi_jobs: 1, serpapi_search: 2 } as const;
  const topSignal = [...signals].sort((a, b) => priority[a.source] - priority[b.source])[0];
  const hook = topSignal
    ? `Saw that ${lead.company_name} ${
        topSignal.source === "serpapi_jobs"
          ? `is hiring for "${topSignal.headline.replace(lead.company_name, "").trim()}"`
          : `— "${topSignal.headline}"`
      }.`
    : `Came across ${lead.company_name} recently.`;

  const body = `Hi ${lead.contact_name.split(" ")[0]},

${hook} Congrats on the momentum.

We work with teams at similar-stage companies to cut the manual work out of ${
    lead.contact_title?.toLowerCase().includes("ops") ? "operations" : "go-to-market"
  }. Given what's happening at ${lead.company_name} right now, this felt timely to reach out.

Worth a 15-minute call this week to see if it's a fit?

Best,
[Your name]`;

  return {
    subject: `${lead.company_name} + a quick idea`,
    body,
    generated_by: "template_fallback" as const,
  };
}
